import Config

# Configure your database
config :interview, Interview.Repo,
  username: System.get_env("PGUSER", System.get_env("USER")),
  password: System.get_env("PGPASSWORD", ""),
  hostname: System.get_env("PGHOST", "localhost"),
  database: System.get_env("PGDATABASE", "interview_dev"),
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :interview, InterviewWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "bR8p26PFBdXLmqsbUyvWX7Rk04igumMm6GUEysBXJQgIetppAWHyfnI1luqKSKxK",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:interview, ~w(--sourcemap=inline --watch)]},
    embed_esbuild: {Esbuild, :install_and_run, [:embed, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:interview, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :interview, InterviewWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/interview_web/router\.ex$"E,
      ~r"lib/interview_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :interview, dev_routes: true

# Phase-0 third-party iframe harness (separate origin, port 5174).
# See lib/interview_web/harness_router.ex.
config :interview, :harness_enabled, true
config :interview, :harness_port, 5174

# Webhook URL policy — dev convenience: allow http:// and private/loopback
# destinations so a local receiver (e.g. http://localhost:3000/hook) works
# without ceremony. Prod keeps the strict default.
config :interview, Interview.Webhooks,
  allow_http_urls: true,
  allow_private_destinations: true

# Phase-4 soak telemetry handler (Interview.SoakTelemetry).
# Pretty-prints recorder + webhook events so a local soak run leaves
# a chronological trail in the dev console without extra plumbing.
config :interview, :soak_telemetry, true

# Allow the harness origin to embed the recorder. Production resolves
# this per-tenant from the DB; dev keeps a static list. See PLAN §4.4.
config :interview, :embed_frame_ancestors, [
  "'self'",
  "http://127.0.0.1:5174",
  "http://localhost:5174"
]

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
